#ifndef POKEPLATINUM_CONSTANTS_STRING_H
#define POKEPLATINUM_CONSTANTS_STRING_H

#define MON_NAME_LEN         10
#define TRAINER_NAME_LEN     7
#define TRAINER_NAME_LEN_LONGER 12
#define TABLET_NAME_LEN      10
#define MOVE_NAME_LEN        16
#define UNION_GROUP_NAME_LEN 7
#define BOX_NAME_LEN         8

#endif
